backend:
  name: github
  repo: muhammetnur2002/uliana-english.com # ОБЯЗАТЕЛЬНО: Проверьте, что это ваш репозиторий
  branch: main 
  base_url: https://github.com 

media_folder: "static/img"
public_folder: "/static/img"

collections:
  - name: "site_content"
    label: "Общие настройки сайта"
    files:
      - file: "src/_data/about.json" 
        label: "Обо Мне"
        name: "about_section"
        fields:
          - {label: "Заголовок раздела", name: "title", widget: "string", default: "Обо Мне"}
          - {label: "Опыт работы", name: "experience", widget: "number", default: 5}
          - {label: "Основной текст о себе", name: "main_text", widget: "markdown", required: true}
